#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2

source deactivate

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# Summarising BIOM
echo "Summarising .BIOM"
time biom summarize-table -i /home/cbmucl15/2018_02_smb/opened_otus_SILVA/otu_table_mc2_w_tax_no_pynast_failures.biom -o /home/cbmucl15/2018_02_smb/opened_otus_SILVA/opened_otu_table_summary.txt

source deactivate
